baseURL: 'https://example.org/'
languageCode: 'en-us'
title: 'THIS IS FROM CONFIG.TOML - Building a Site and Theme From ther Beginning with AL - A Journey'
theme: 'my-theme'

taxonomies:
  category: 'categories'
  tag: 'tags'

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1

    - identifier: blog
      name: Blog
      url: "/posts/"
      weight: 2

    - identifier: about
      name: About
      url: "/about/"
      weight: 3
      
    - identifier: contact
      name: Contact
      url: "/contact/"
      weight: 4