baseURL: 'https://example.org/'
languageCode: 'en-us'
title: 'Building a Hugo Site and Theme From ther Beginning with AL - A Journey'
theme: 'my-theme'

params:
  wordsPerMinute: 200  # Adjust this value to customize reading speed - 260 is the average reading speed
  dateFormat: "02-01-2006"  # Date format for posts

taxonomies:
  category: 'categories'
  tag: 'tags'

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1

    - identifier: blog
      name: Blog
      url: "/posts/"
      weight: 2

    - identifier: about
      name: About
      url: "/about/"
      weight: 3