baseURL: 'https://example.org/'
languageCode: 'en-us'
title: 'Building a Hugo Site and Theme From ther Beginning with AL - A Journey'
theme: 'my-theme'

params:
  wordsPerMinute: 200  # Adjust this value to customize reading speed - 260 is the average reading speed
  dateFormat: "02-01-2006"  # Date format for posts

  name: "Andy Jenkins"
  bio: "Principal Technology Specialist"
  profileImage: "images/profile.jpg"

  social:
    - name: "GitHub"
      url: "https://github.com/yourusername"
      icon: "fa-brands fa-github"

    - name: "X (Twitter)"
      url: "https://x.com/yourusername"
      icon: "fa-brands fa-x-twitter"

    - name: "LinkedIn"
      url: "https://linkedin.com/in/yourusername"
      icon: "fa-brands fa-linkedin"

taxonomies:
  category: 'categories'
  tag: 'tags'

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1

    - identifier: blog
      name: Blog
      url: "/posts/"
      weight: 2

    - identifier: about
      name: About
      url: "/about/"
      weight: 3